<%
Function ImageSize(strFileName, Height, Width)
'	Dim Img
'    set Img = Server.CreateObject ("ImgSize.Check")
'    Img.FileName = strFileName
'    if Img.Error <> "" then
'	ImageSize = false
'      Response.Write "에러 발생?<br>"
 '     Response.Write "에러는<b>" & Img.Error & "</b>"
'    else
'      'Response.Write "<p>Image <b>" & strFileName & "</b> successfully read.<br>"
'	ImageSize = true
'      Height =Img.Height
'      Width = img.Width
  '    Response.Write "Image Height = <b>" & Height & "</b><br>"
   '  Response.Write "Image Width  = <b>" & Width & "</b></p>"
'    end if
'    set Img = nothing
End Function
%>


